services:
  frontend:
    container_name: frontend-dev
    image: todo-frontend-dev
    build:
      context: ./todo-frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-frontend:/usr/src/app
  backend:
    container_name: todo-backend
    build:
      context: ./todo-backend
      dockerfile: dev.Dockerfile
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://the_username:the_password@mongodb:27017/todo_db
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./todo-backend:/usr/src/app
    depends_on:
      - mongodb
      - redis
  nginx:
    container_name: reverse-proxy-dev
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - frontend
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: todo_db
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - redis_data:/data
  debug-helper:
    container_name: debug-helper
    image: busybox

volumes:
  mongo_data:
  redis_data: