services:
  todo-backend:
    container_name: todo-backend
    build:
      context: ./
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongodb:27017/todo_db
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./:/usr/src/app
    depends_on:
      - mongodb
      - redis
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - ${MONGO_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    env_file:
      - ./.env
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
  redis:
    container_name: redis
    image: redis
    ports:
      - ${REDIS_PORT}:6379
    env_file:
      - ./.env
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - redis_data:/data
  debug-helper:
    container_name: debug-helper
    image: busybox

volumes:
  mongo_data:
  redis_data: