services:
  mongodb:
    image: mongo
    ports:
      - ${MONGO_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    env_file:
      - ./.env
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
  redis:
    image: redis
    ports:
      - ${REDIS_PORT}:6379
    env_file:
      - ./.env
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data: